const POEMS=[
{id:'waterfall',title:'望庐山瀑布',author:'李白',dynasty:'唐',grade:'二年级',source:'grade',style:'山水',season:'夏',text:'日照香炉生紫烟，\n遥看瀑布挂前川。\n飞流直下三千尺，\n疑是银河落九天。',excerpt:'飞流直下三千尺，疑是银河落九天。',summary:'李白把眼前瀑布写成从天而降的银河，让一座山有了奔涌的想象。',analysis:'前两句从阳光、香炉峰与远望铺开画面；“飞流”“三千尺”写出瀑布的速度与高度，“疑是”把真实山水推入浪漫想象。',bio:'李白是盛唐最具想象力的诗人之一，一生漫游名山大川。奔腾的庐山瀑布，正合他的豪迈气质。',image:'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=1000&q=85',quiz:[['“疑是银河落九天”运用了什么修辞？',['比喻和夸张','拟人','排比'],0],['诗人从什么角度观看瀑布？',['近处仰望','远处遥望','水中倒影'],1],['“飞流”表现瀑布怎样的特点？',['缓慢安静','迅疾壮阔','细小轻柔'],1]]},
{id:'dawn',title:'春晓',author:'孟浩然',dynasty:'唐',grade:'一年级',source:'grade',style:'田园',season:'春',text:'春眠不觉晓，\n处处闻啼鸟。\n夜来风雨声，\n花落知多少。',excerpt:'春眠不觉晓，处处闻啼鸟。',summary:'在鸟鸣中醒来，诗人由清晨的声音想到昨夜风雨与落花。',analysis:'诗中没有直接写春色，却用“春眠”“啼鸟”“风雨”“花落”串起一个有声有感的早晨。结尾的疑问带着对春光的爱惜。',bio:'孟浩然是盛唐山水田园诗人，诗风自然清淡，常从日常小景里写出安静而真切的情绪。',image:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1000&q=85',quiz:[['“处处闻啼鸟”描写哪个时刻？',['春天清晨','夏日正午','秋天夜晚'],0],['诗人因何想到花落？',['看见落花','听见昨夜风雨','朋友告诉他'],1],['全诗表达对春天怎样的情感？',['厌烦','喜爱与怜惜','害怕'],1]]},
{id:'night',title:'静夜思',author:'李白',dynasty:'唐',grade:'一年级',source:'grade',style:'思乡',season:'秋',text:'床前明月光，\n疑是地上霜。\n举头望明月，\n低头思故乡。',excerpt:'举头望明月，低头思故乡。',summary:'一轮明月照在异乡人的窗前，也照出了最朴素的思乡心绪。',analysis:'“举头”与“低头”形成动作上的对照：先看见明月，后想起故乡。语言极简，却让月光与乡愁紧紧相连。',bio:'李白长期在外游历，月亮常出现在他的诗中。这首小诗以人人都见过的月色，道出人人都懂的想家。',image:'https://images.unsplash.com/photo-1519608487953-e999c86e7454?auto=format&fit=crop&w=1000&q=85',quiz:[['诗中哪两个动作形成对照？',['坐下和起身','举头和低头','走路和停步'],1],['月光像什么？',['明亮的霜','火焰','流水'],0],['诗人看到明月后想什么？',['故乡','瀑布','风筝'],0]]},
{id:'deer',title:'鹿柴',author:'王维',dynasty:'唐',grade:'课外推荐',source:'extra',style:'山水',season:'秋',text:'空山不见人，\n但闻人语响。\n返景入深林，\n复照青苔上。',excerpt:'空山不见人，但闻人语响。',summary:'空山似乎无人，偏偏传来人声；一束夕阳，又照亮幽深林间的青苔。',analysis:'诗人用“人语响”反衬山的空寂，用斜阳照青苔写出幽深。声音与光线让画面越发宁静。',bio:'王维精于山水诗，也擅长绘画。他的诗常像留白的画面，于极静之中藏着细微的声光。',image:'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1000&q=85',quiz:[['“返景”指什么？',['返照的阳光','回家的景色','倒映水光'],0],['“人语响”有什么作用？',['反衬山中空寂','写集市热闹','介绍朋友'],0],['最后被阳光照亮什么？',['青苔','瀑布','纸鸢'],0]]},
{id:'snow',title:'江雪',author:'柳宗元',dynasty:'唐',grade:'课外推荐',source:'extra',style:'孤寂',season:'冬',text:'千山鸟飞绝，\n万径人踪灭。\n孤舟蓑笠翁，\n独钓寒江雪。',excerpt:'孤舟蓑笠翁，独钓寒江雪。',summary:'千万座山没有鸟影，万条路没有行人，只有一位老翁在雪江独钓。',analysis:'前两句用“千山”“万径”写出无边空阔，后两句聚焦一叶孤舟。极大的空间与极小的人影相对，显出清冷而坚守的力量。',bio:'柳宗元在被贬永州期间写下许多山水诗。《江雪》的孤舟老翁，也寄寓着诗人清醒自守的心境。',image:'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1000&q=85',quiz:[['环境最突出的特点？',['热闹繁华','空阔寂静','温暖明亮'],1],['江上钓鱼的是谁？',['蓑笠翁','小孩','朋友'],0],['“千山”“万径”有什么作用？',['写范围广大','写数字计算','写山路拥挤'],0]]},
{id:'drinking',title:'饮酒·其五',author:'陶渊明',dynasty:'东晋',grade:'进阶学习',source:'advanced',style:'田园',season:'秋',text:'结庐在人境，\n而无车马喧。\n问君何能尔？\n心远地自偏。',excerpt:'问君何能尔？心远地自偏。',summary:'住在人间却能远离喧扰，关键不在住处，而在一颗安静自守的心。',analysis:'诗人以设问自答点出“心远”：内心远离功名纷扰，居处自然显得偏静。语气平淡，思想却很深。',bio:'陶渊明是东晋田园诗人，曾短暂为官，后归隐耕读。他的诗塑造了质朴、自在的田园精神。',image:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=85',quiz:[['“心远”指什么？',['距离遥远','远离世俗喧扰','住得很远'],1],['安静的关键是什么？',['换房子','内心宁静','没有邻居'],1],['陶渊明常写哪类生活？',['田园生活','战场生活','宫廷生活'],0]]},
{id:'orieles',title:'绝句',author:'杜甫',dynasty:'唐',grade:'三年级',source:'grade',style:'写景',season:'春',text:'两个黄鹂鸣翠柳，\n一行白鹭上青天。\n窗含西岭千秋雪，\n门泊东吴万里船。',excerpt:'窗含西岭千秋雪，门泊东吴万里船。',summary:'杜甫从窗前鸟语写到远山积雪、江上船只，把一方小院打开成辽阔的春天。',analysis:'前两句以黄、翠、白、青四种色彩构成明丽画面；后两句把“窗”与“门”化作取景框，远近相衬，动静相生。',bio:'杜甫经历安史之乱，诗中常有关怀现实的厚重；这首《绝句》写于成都草堂，呈现出难得的明净与开阔。',image:'https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?auto=format&fit=crop&w=1000&q=85',quiz:[['诗中出现了几种颜色？',['两种','三种','四种'],2],['“窗含”写出了怎样的画面？',['从窗望见远山积雪','窗上结了冰','窗内有一幅画'],0],['“万里船”表现了什么？',['船停得很近','水路与远方相连','船很小'],1]]},
{id:'west-hill',title:'题西林壁',author:'苏轼',dynasty:'宋',grade:'四年级',source:'grade',style:'哲理',season:'秋',text:'横看成岭侧成峰，\n远近高低各不同。\n不识庐山真面目，\n只缘身在此山中。',excerpt:'不识庐山真面目，只缘身在此山中。',summary:'同一座庐山，从不同角度看会有不同样子；苏轼由此悟出看事物要跳出局部。',analysis:'前两句写观察位置不同，山形便不同；后两句由景入理，告诉我们身处事物之中时，容易被局部遮住全貌。',bio:'苏轼是北宋文学家、书画家，经历起伏却始终旷达。他的诗善于把眼前景物化为开阔的人生思考。',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85',quiz:[['为什么看不清庐山真面目？',['山太高','身在山中','天气不好'],1],['诗中蕴含什么道理？',['观察要换角度','山里没有路','船比山重要'],0],['这首诗主要写什么？',['送别','哲理','节日'],1]]},
{id:'shepherd',title:'牧童',author:'吕岩',dynasty:'唐',grade:'五年级',source:'grade',style:'田园',season:'夏',text:'草铺横野六七里，\n笛弄晚风三四声。\n归来饱饭黄昏后，\n不脱蓑衣卧月明。',excerpt:'不脱蓑衣卧月明。',summary:'辽阔草野、晚风笛声与月下牧童，写出一种自在无拘的乡野生活。',analysis:'“铺”字写草色无边，“弄”字让笛声仿佛与晚风玩耍。最后牧童不脱蓑衣卧月明，是全诗最闲适的一笔。',bio:'吕岩又名吕洞宾，传说色彩浓厚。传世诗中常有超脱、闲适的意趣，《牧童》尤其贴近儿童可感的田园画面。',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85',quiz:[['“草铺横野”写草地怎样？',['很狭窄','无边开阔','没有草'],1],['牧童在何时归来？',['清晨','正午','黄昏后'],2],['“不脱蓑衣卧月明”表现什么？',['闲适自在','十分害怕','急着赶路'],0]]},
{id:'lime',title:'石灰吟',author:'于谦',dynasty:'明',grade:'六年级',source:'grade',style:'咏物',season:'冬',text:'千锤万凿出深山，\n烈火焚烧若等闲。\n粉骨碎身浑不怕，\n要留清白在人间。',excerpt:'粉骨碎身浑不怕，要留清白在人间。',summary:'诗人借石灰经受锤凿烈火仍保持洁白，写出坚守清白、不畏牺牲的志向。',analysis:'前两句写石灰开采、煅烧的艰难过程，后两句由物及人。“清白”既写石灰颜色，也象征人格操守。',bio:'于谦是明代名臣，曾在国家危急时主持北京保卫战。《石灰吟》以托物言志，表达了他清正坚毅的品格。',image:'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1000&q=85',quiz:[['“清白”在诗中象征什么？',['雪的颜色','人格操守','石头重量'],1],['这首诗采用什么写法？',['托物言志','写景抒情','送别怀人'],0],['“浑不怕”表现怎样的精神？',['畏惧退缩','不怕牺牲','犹豫不决'],1]]}
];
const $=s=>document.querySelector(s),find=id=>POEMS.find(p=>p.id===id),restore=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},state={daily:'waterfall',source:'all',current:'waterfall',group:'elementary',chip:'全部',historyPage:'early',recent:restore('poetry-recent',['waterfall','dawn']),done:restore('poetry-done',[]),stats:restore('poetry-stats',{}),quiz:[],index:0};
const taxonomy={
	waterfall:{topics:['山水田园诗'],form:'七言绝句',era:'唐诗',objects:['山川','水']},
	dawn:{topics:['山水田园诗'],form:'五言绝句',era:'唐诗',objects:['春天','鸟']},
	night:{topics:['思乡怀亲诗'],form:'五言绝句',era:'唐诗',objects:['月亮','秋天']},
	deer:{topics:['山水田园诗'],form:'五言绝句',era:'唐诗',objects:['山川','树木','光影']},
	snow:{topics:['山水田园诗'],form:'五言绝句',era:'唐诗',objects:['冬天','雪']},
	drinking:{topics:['山水田园诗','哲理说理诗'],form:'五言古诗',era:'魏晋诗',objects:['花木','秋天']}
	,orieles:{topics:['山水田园诗'],form:'七言绝句',era:'唐诗',objects:['春天','鸟','雪']}
	,'west-hill':{topics:['哲理说理诗','山水田园诗'],form:'七言绝句',era:'宋诗',objects:['山川']}
	,shepherd:{topics:['童真童趣诗','山水田园诗'],form:'七言绝句',era:'唐诗',objects:['夏天','儿童','月亮']}
	,lime:{topics:['咏物言志诗'],form:'七言绝句',era:'元明清',objects:['山川','火']}
};
const detailImages={
	waterfall:['https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=85'],
	dawn:['https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=900&q=85'],
	night:['https://images.unsplash.com/photo-1519608487953-e999c86e7454?auto=format&fit=crop&w=900&q=85'],
	deer:['https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=85'],
	snow:['https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=85'],
	drinking:['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85'],
	orieles:['https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?auto=format&fit=crop&w=900&q=85'],
	'west-hill':['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85'],
	shepherd:['https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=85'],
	lime:['https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=900&q=85']
};
const dailyPhrases=[
	p=>`跟着${p.author}的笔墨，从《${p.title}》走进一幅有声有色的画。`,
	p=>`今天不求读多，只把《${p.title}》的一句诗读到心里。`,
	p=>`从${p.dynasty}的一页诗卷开始，和《${p.title}》相遇。`,
	p=>`看${p.style}里的光与风，在《${p.title}》中发现新的远方。`
];
const readingNotes={
	waterfall:{pinyin:'rì zhào xiāng lú shēng zǐ yān，yáo kàn pù bù guà qián chuān。\nfēi liú zhí xià sān qiān chǐ，yí shì yín hé luò jiǔ tiān。',deep:'“生”字让紫烟仿佛从香炉峰缓缓升起；“挂”字把远望中的瀑布定格成白练。后两句从实景跃入神话想象，“飞流”写动态，“三千尺”用夸张扩张高度，“银河落九天”让瀑布获得了天外来客般的气势。',background:'此诗约作于李白游庐山时。庐山瀑布落差大、声势足，正契合诗人浪漫豪放的表达方式。诗人并不说明行程，而是用视觉层层推远，让读者在四句中完成一次仰望。'},
	dawn:{pinyin:'chūn mián bù jué xiǎo，chù chù wén tí niǎo。\nyè lái fēng yǔ shēng，huā luò zhī duō shǎo。',deep:'全诗从“醒来”开始，却不直写所见春景，而是听鸟声、忆风雨、想落花。前两句由室内到室外，后两句由此刻回到昨夜；“知多少”的轻问不是计算，而是对春光易逝的怜惜。',background:'孟浩然长期隐居、漫游，擅长从日常感受中写自然。这首诗传为春晨醒后所作，语言像闲谈一样自然，却把时间、声音和惜春之情织得十分完整。'},
	night:{pinyin:'chuáng qián míng yuè guāng，yí shì dì shàng shuāng。\njǔ tóu wàng míng yuè，dī tóu sī gù xiāng。',deep:'前两句把月光误认成霜，写出夜深月明的清冷；后两句只有“举头”“低头”两个动作，却完成了从看月到想家的情绪转折。明月是眼前景，也成为连接异乡与故乡的共同意象。',background:'李白一生多在漫游途中，月亮反复出现在他的诗里。《静夜思》以极简的语言写出普遍的乡愁，因此成为最广为传诵的唐诗之一。'},
	deer:{pinyin:'kōng shān bú jiàn rén，dàn wén rén yǔ xiǎng。\nfǎn jǐng rù shēn lín，fù zhào qīng tái shàng。',deep:'“不见人”却“闻人语”，声音反而衬出空山的幽静；“返景”是夕阳返照，光线进入深林又落到青苔上。诗人用人声和光影两种微小变化，写出山林深处的空灵。',background:'王维既是诗人也是画家，晚年常居辋川别业。《鹿柴》所在的组诗多写辋川景物，诗中留白、光色与空间感，也体现了他诗画相通的审美。'},
	snow:{pinyin:'qiān shān niǎo fēi jué，wàn jìng rén zōng miè。\ngū zhōu suō lì wēng，dú diào hán jiāng xuě。',deep:'“千山”“万径”先把空间推到极大，“绝”“灭”又把鸟与人全部抹去；镜头最终落到一叶孤舟、一个老翁。“孤”“独”并非只写寂寞，也写出在严寒中自守不移的姿态。',background:'柳宗元被贬永州期间，长期处在政治失意中。他借山水写心境，《江雪》的冰雪世界既是客观景色，也折射出诗人清醒、孤峭的精神姿态。'},
	drinking:{pinyin:'jié lú zài rén jìng，ér wú chē mǎ xuān。\nwèn jūn hé néng ěr？xīn yuǎn dì zì piān。',deep:'诗人先写“在人境”，却没有车马喧闹，形成看似矛盾的开端。设问之后以“心远”作答：并非地理位置偏远，而是内心摆脱了功名纷扰，所以普通居处也成为安静之地。',background:'陶渊明厌倦仕途后归隐田园。《饮酒》组诗写在归隐时期，以饮酒为名，实际思考的是如何在现实世界中保持心灵的自由与清醒。'},
	orieles:{pinyin:'liǎng gè huáng lí míng cuì liǔ，yì háng bái lù shàng qīng tiān。\nchuāng hán xī lǐng qiān qiū xuě，mén bó dōng wú wàn lǐ chuán。',deep:'前两句以黄、翠、白、青四种颜色构成鲜明画面，鸟的鸣叫与飞行让春天充满生机。后两句将“窗”“门”化作取景框：一边含纳千秋雪山，一边停泊通往万里的船只，近景与远景同时展开。',background:'此诗作于杜甫寓居成都草堂期间。经历战乱后，诗人在相对安定的生活中重新感受到春日明丽；诗中明净的色彩背后，仍有对辽阔山河与远方行旅的关注。'},
	'west-hill':{pinyin:'héng kàn chéng lǐng cè chéng fēng，yuǎn jìn gāo dī gè bù tóng。\nbù shí lú shān zhēn miàn mù，zhǐ yuán shēn zài cǐ shān zhōng。',deep:'前两句写观察角度改变，山的形态便不同。“横看”“侧看”“远近高低”不是重复，而是提示我们任何所见都带有位置限制。后两句从庐山写到认识方法：身处局部，往往难见全貌。',background:'苏轼游庐山时题写此诗。北宋文人常在山水中讨论人生与知识，这首诗将旅行体验化成通俗而深刻的认识论，因此成为小学阶段常见的哲理诗。'},
	shepherd:{pinyin:'cǎo pù héng yě liù qī lǐ，dí nòng wǎn fēng sān sì shēng。\nguī lái bǎo fàn huáng hūn hòu，bù tuō suō yī wò yuè míng。',deep:'“铺”字写草野连绵，“弄”字让笛声和晚风都带上了玩耍的意味。末句没有写牧童的表情，只写他穿着蓑衣卧在月光下，悠闲自在的童趣便自然流露出来。',background:'《牧童》作者吕岩常被称作吕洞宾，作品带有闲适超脱的意趣。此诗选择牧童一天中最放松的黄昏片段，把乡野生活写得开阔、轻松。'},
	lime:{pinyin:'qiān chuí wàn záo chū shēn shān，liè huǒ fén shāo ruò děng xián。\nfěn gǔ suì shēn hún bú pà，yào liú qīng bái zài rén jiān。',deep:'“千锤万凿”“烈火焚烧”先写石灰的形成过程，再以“粉骨碎身”推进到极致。“清白”一语双关：表面写石灰洁白，深层写人应坚守操守。全诗借物言志，层层由物及人。',background:'于谦是明代名臣，曾在北京保卫战中发挥重要作用。他一生以清正著称，《石灰吟》虽写石灰，却集中表达了不惧艰难、坚守人格的志向。'}
};
const topicNames=['山水田园诗','送别抒怀诗','思乡怀亲诗','爱国・边塞诗','咏物言志诗','童真童趣诗','传统节日诗','哲理说理诗','咏史怀古诗','亲情民生诗'];
const topicScenes={
	'山水田园诗':['山水田园','山川、四季与农家日常，让诗意先抵达眼前。','waterfall'],
	'送别抒怀诗':['送别抒怀','在江边、驿路与远帆之间，读懂惜别与祝愿。','night'],
	'思乡怀亲诗':['思乡怀亲','一轮月、一声雁，都可能牵出故园与亲人的方向。','night'],
	'爱国・边塞诗':['爱国・边塞','把边关风雪、家国担当与壮志豪情读得更有力量。','snow'],
	'咏物言志诗':['咏物言志','借梅、竹、石与小小生灵，照见人格与志向。','drinking'],
	'童真童趣诗':['童真童趣','放纸鸢、弄冰、垂钓，诗里的童年明亮又鲜活。','dawn'],
	'传统节日诗':['传统节日','沿着春节、清明、七夕、中秋与重阳，认识古人的节令生活。','night'],
	'哲理说理诗':['哲理说理','在山水与日常里，发现一句值得慢慢想的道理。','drinking'],
	'咏史怀古诗':['咏史怀古','登临旧地，回望人物与兴亡，感受时间留下的回声。','snow'],
	'亲情民生诗':['亲情民生','从母爱、劳作到百姓生活，读见最朴实的人间关怀。','dawn']
};
const schoolData=[
	['浪漫主义','李白','以雄奇想象、夸张比喻写山河与人生。',['waterfall','night'],'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=85'],
	['山水田园派','王维 · 孟浩然 · 陶渊明','以清景、闲情与留白，写出自然里的安静力量。',['deer','dawn','drinking'],'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=85'],
	['现实主义','杜甫','以沉郁写实关照家国与民生。',['orieles'],'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=85'],
	['边塞诗派','王昌龄 · 王之涣','以边关风雪与英雄气概拓开壮阔视野。',['snow'],'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=85'],
	['豪放词派','苏轼 · 辛弃疾','以开阔意境与壮志情怀写人生。',['west-hill'],'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=500&q=85'],
	['婉约词派','李清照 · 纳兰性德','以细腻情思、曲折意境见长。',['night'],'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=85']
];
const timeline=[
	['early','诗经与楚辞','前11世纪—前206','从《诗经》的民歌采集到屈原的楚辞想象，诗歌奠定了“言志”“缘情”的传统。',[]],
	['early','汉乐府设立','前206—220','汉武帝时期设置乐府，民间歌谣被采录。现实生活、劳动与战争进入诗歌。',[]],
	['early','建安风骨','196—220','战乱与理想交织，曹操、曹植等人开创慷慨悲凉的建安文学。',[]],
	['early','魏晋风度','220—420','政治动荡中，诗人转向人格、自然与精神世界；陶渊明以田园诗树立典范。',['drinking']],
	['early','南北朝民歌','420—589','北朝民歌质朴雄健，南朝民歌清丽婉转，民歌传统继续滋养诗歌。',[]],
	['early','大唐建立','618','唐朝建立，科举、城市与开放的文化交流，为诗歌全面繁荣创造了条件。',[]],
	['early','盛唐气象','713—755','开元盛世孕育浪漫、山水与田园等多种诗歌风貌，李白、王维、孟浩然等相继出现。',['dawn','deer','waterfall','night']],
	['late','安史之乱','755','社会巨变后，诗歌更深切地关照漂泊、战争与民生，杜甫的现实主义写作尤为重要。',['orieles','snow']],
	['late','中晚唐转向','766—907','古文运动、讽喻诗与小诗并行，诗歌的社会关怀与艺术精炼不断推进。',[]],
	['late','北宋建立','960','宋代文人文化兴盛，诗歌与散文、书画相互滋养，重理趣与日常观察。',['west-hill']],
	['late','靖康之变','1127','南宋偏安后，陆游、辛弃疾等以诗词写下家国忧思，豪放词获得新力量。',[]],
	['late','元代文艺转场','1271—1368','戏曲兴盛，诗词仍持续创作；文人表达更多转入山林、怀古与日常。',[]],
	['late','明清诗歌延展','1368—1912','明清诗社、家国变局与个性表达并存，于谦等人的诗作留下了鲜明的时代人格。',['lime']]
];
const objectNames=['月亮','春天','夏天','秋天','冬天','花木','山川','水','鸟','树木','风雨','雪','儿童'];
const topicsOf=p=>taxonomy[p.id]?.topics||[],objectsOf=p=>taxonomy[p.id]?.objects||[],topicOf=p=>topicsOf(p)[0]||p.style,formOf=p=>taxonomy[p.id]?.form||'未归类',eraOf=p=>taxonomy[p.id]?.era||'未归类';
function save(){localStorage.setItem('poetry-recent',JSON.stringify(state.recent));localStorage.setItem('poetry-done',JSON.stringify(state.done));localStorage.setItem('poetry-stats',JSON.stringify(state.stats))} function related(p){return POEMS.filter(x=>x.id!==p.id&&(x.author===p.author||x.style===p.style)).slice(0,3)} function relCard(p){return `<button class="related-poem" type="button" data-poem="${p.id}" style="--poem-image:url('${p.image}')"><em>${p.author===find(state.current).author?'同一诗人':'相近意境'}</em><strong>${p.title}</strong><small>${p.author} · ${p.dynasty}</small></button>`}
function view(name){document.querySelectorAll('main > section').forEach(x=>x.classList.add('hidden'));$(`#${name}-view`).classList.remove('hidden');document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));if(name==='shelf')shelf();if(name==='progress')progress();if(name==='collection')collection();window.scrollTo({top:0,behavior:'smooth'})}
function daily(){const p=find(state.daily);const phrase=dailyPhrases[Math.floor(Math.random()*dailyPhrases.length)](p);$('#daily-label').textContent=`今日鉴赏 · ${p.dynasty} · ${p.grade}`;$('#daily-headline').textContent=phrase;$('#daily-summary').textContent=p.summary;$('#daily-image').src=p.image;$('#daily-quote').textContent=p.excerpt.split('，')[0];$('#daily-title').textContent=p.title;$('#related-subtitle').textContent=`沿着${p.author}与“${topicOf(p)}”的线索，再读几首。`;$('#home-related').innerHTML=related(p).map(relCard).join('')}
function matchesSearch(p){const term=$('#poem-search').value.trim();return `${p.title}${p.author}${p.dynasty}${p.text}${topicOf(p)}${formOf(p)}${eraOf(p)}${objectsOf(p).join('')}`.includes(term)}
function poemCard(p){return `<button class="poem-card" type="button" data-poem="${p.id}" style="--poem-image:url('${p.image}')"><span class="tag">${p.dynasty} · ${topicOf(p)} · ${p.grade}</span><h3>${p.title}</h3><p>${p.excerpt}</p><footer><span>${p.author}</span><span>进入学习 →</span></footer></button>`}
function empty(){return '<div class="empty-state">当前示例诗库尚未收录这一类别。<br>可切换其他线索，或用搜索继续查找。</div>'}
function gradeShelf(){const levels=['全部','一年级','二年级','三年级','四年级','五年级','六年级','课外推荐','进阶学习'];const list=POEMS.filter(p=>matchesSearch(p)&&(state.chip==='全部'||p.grade===state.chip));return `<div class="grade-shelf"><p class="eyebrow">循年级而读</p><h2 class="filter-title">小学古诗</h2><p class="filter-intro">从短小好读的绝句开始，逐步走向更宽阔的诗歌世界。</p><div class="grade-steps">${levels.slice(1,7).map((level,index)=>`<button type="button" data-chip="${level}" class="grade-step ${state.chip===level?'active':''}"><b>0${index+1}</b><span>${level}</span></button>`).join('')}</div><div class="chip-row">${levels.map(x=>`<button class="chip ${x===state.chip?'active':''}" data-chip="${x}" type="button">${x}</button>`).join('')}</div><div class="poem-grid">${list.length?list.map(poemCard).join(''):empty()}</div></div>`}
function themeShelf(){const selected=state.chip==='全部'?'山水田园诗':state.chip;const scene=topicScenes[selected];const poem=find(scene[2]);const list=POEMS.filter(p=>matchesSearch(p)&&topicsOf(p).includes(selected));return `<div class="theme-shelf"><div class="topic-atlas">${topicNames.map((name,index)=>`<button type="button" data-chip="${name}" class="topic-tile ${name===selected?'active':''}"><span>${String(index+1).padStart(2,'0')}</span>${name}</button>`).join('')}</div><section class="topic-stage" style="--topic-image:url('${poem.image}')"><p class="eyebrow">考试高频题材</p><h2>${scene[0]}</h2><p>${scene[1]}</p><button class="text-button" type="button" data-chip="全部">返回题材图谱</button></section><div class="poem-grid">${list.length?list.map(poemCard).join(''):empty()}</div></div>`}
function historyShelf(){const filters=['全部','古乐府','五言绝句','七言绝句','五言古诗','律诗','词','汉魏乐府','魏晋诗','唐诗','宋诗','元明清'];const selected=state.chip;const accepts=p=>selected==='全部'||formOf(p)===selected||eraOf(p)===selected;const chapters=state.historyPage==='all'?timeline:timeline.filter(item=>item[0]===state.historyPage);return `<div class="history-shelf"><header class="history-intro"><p class="eyebrow">诗歌与时代同行</p><h2 class="filter-title">体裁与朝代</h2><p class="filter-intro">沿时间轴从古到今，既读诗人的声音，也看历史事件如何改变诗歌。长卷分为上下两卷，方便循序浏览。</p><div class="history-pages"><button type="button" data-history-page="early" class="${state.historyPage==='early'?'active':''}">上卷 · 上古至盛唐</button><button type="button" data-history-page="late" class="${state.historyPage==='late'?'active':''}">下卷 · 中唐至明清</button><button type="button" data-history-page="all" class="${state.historyPage==='all'?'active':''}">全卷 · 纵览</button></div><div class="chip-row">${filters.map(x=>`<button class="chip ${x===selected?'active':''}" data-chip="${x}" type="button">${x}</button>`).join('')}</div></header><div class="timeline">${chapters.map(([,era,date,event,ids])=>{const entries=ids.map(find).filter(p=>matchesSearch(p)&&accepts(p));return `<section class="time-node"><div class="time-stamp"><b>${date}</b><span>${era}</span></div><div class="time-event"><p class="event-label">历史节点</p><p>${event}</p>${entries.length?`<div class="timeline-poems">${entries.map(p=>`<button type="button" data-poem="${p.id}" style="--poem-image:url('${p.image}')"><strong>${p.title}</strong><small>${p.author} · ${formOf(p)}</small></button>`).join('')}</div>`:''}</div></section>`}).join('')}</div></div>`}
function schoolShelf(){return `<div class="school-shelf"><p class="eyebrow">从诗人读到诗派</p><h2 class="filter-title">风格与派系</h2><p class="filter-intro">不把诗人孤立来看。相近的审美、题材和写法，会汇成一条诗歌传统。</p><div class="school-grid">${schoolData.map(([name,authors,description,reps,portrait],index)=>`<article class="school-card school-${index%3}"><img class="school-portrait" src="${portrait}" alt="${authors}诗人画意象" /><p>${String(index+1).padStart(2,'0')} · ${name}</p><h3>${authors}</h3><span>${description}</span><div>${reps.map(rep=>{const poem=find(rep);return poem?`<button class="text-button" type="button" data-poem="${poem.id}">《${poem.title}》</button>`:`<small>${rep}</small>`}).join('')}</div></article>`).join('')}</div></div>`}
function objectShelf(){const selected=state.chip==='全部'?'月亮':state.chip;const list=POEMS.filter(p=>matchesSearch(p)&&objectsOf(p).includes(selected));const feature=list[0]||find('night');return `<div class="object-shelf"><p class="eyebrow">从一物进入一首诗</p><h2 class="filter-title">古诗与物</h2><p class="filter-intro">月亮、四季、花木、山川与细小生灵，都是古诗中反复出现的意象线索。</p><div class="object-orbit">${objectNames.map((name,index)=>`<button type="button" data-chip="${name}" class="object-token ${name===selected?'active':''}"><b>${['月','春','夏','秋','冬','花','山','水','鸟','木','雨','雪','童'][index]}</b><span>${name}</span></button>`).join('')}</div><section class="object-feature" style="--object-image:url('${feature.image}')"><div><p class="eyebrow">意象 · ${selected}</p><h3>${selected}在诗里</h3><p>${list.length?`从《${feature.title}》开始，顺着一个具体的物，读它如何变成情绪与记忆。`:'这个意象的代表诗正在整理，先从相近意象开始探索。'}</p></div></section><div class="poem-grid">${list.length?list.map(poemCard).join(''):empty()}</div></div>`}
function shelf(){const content=$('#shelf-content');content.className=`shelf-content shelf-${state.group}`;content.innerHTML=state.group==='elementary'?gradeShelf():state.group==='theme'?themeShelf():state.group==='history'?historyShelf():state.group==='schools'?schoolShelf():objectShelf()}
function familiarity(id){const metric=state.stats[id]||{views:0,attempts:0,correct:0};const completion=state.done.includes(id)?35:0;const views=Math.min(metric.views*8,25);const accuracy=metric.attempts?Math.round((metric.correct/metric.attempts)*40):0;const score=Math.min(100,completion+views+accuracy);const label=score<25?'初识':score<50?'渐熟':score<80?'熟悉':score<95?'掌握':'诗友';const copy=`浏览 ${metric.views} 次 · 答题正确率 ${metric.attempts?Math.round(metric.correct/metric.attempts*100):0}%${state.done.includes(id)?' · 已完成深度学习':''}`;return {score,label,copy}}
function open(id){const p=find(id),note=readingNotes[id]||{},metric=state.stats[id]||{views:0,attempts:0,correct:0};metric.views+=1;state.stats[id]=metric;state.current=id;state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,6);save();const fluency=familiarity(id),verses=p.text.split('\n'),pinyin=(note.pinyin||'').match(/[^，。！？\n]+[，。！？]?/g)||[];$('#detail-paper').style.setProperty('--detail-image',`url('${p.image}')`);$('#detail-dynasty').textContent=`${p.dynasty} · ${p.author}`;$('#detail-title').textContent=p.title;$('#detail-meta').textContent=`${p.grade} · ${topicOf(p)} · ${formOf(p)}`;$('#detail-lines').innerHTML=verses.map((verse,index)=>`<p class="poem-line"><span class="line-pinyin">${pinyin[index]||''}</span><span class="line-text">${verse}</span></p>`).join('');$('#familiarity-label').textContent=`${fluency.label} · ${fluency.score}%`;$('#familiarity-bar').style.width=`${fluency.score}%`;$('#familiarity-copy').textContent=fluency.copy;$('#familiarity-toggle').classList.remove('expanded');$('#familiarity-toggle').setAttribute('aria-expanded','false');$('#detail-analysis').textContent=p.analysis;$('#detail-deep-analysis').textContent=note.deep||p.analysis;$('#detail-background').textContent=note.background||p.bio;$('#detail-author').textContent=p.bio;$('#detail-related-list').innerHTML=related(p).map(relCard).join('');view('detail')}
function progress(){$('#learned-count').textContent=state.done.length;$('#streak-count').textContent=Math.max(7,state.done.length+5);$('#study-overview').textContent=state.done.length?`你已完成 ${state.done.length} 首古诗的深度学习。最近读过的诗在下方，点击即可继续。`:'先选一首喜欢的诗开始。完成深度学习后，它会被收入你的个人书架。';$('#recent-study').innerHTML=state.recent.map(id=>{const p=find(id),done=state.done.includes(id);return `<button class="study-card" data-poem="${id}" type="button" style="--poem-image:url('${p.image}')"><h3>${p.title}${done?' · 已完成':''}</h3><p>${p.author} · ${p.dynasty}</p><div class="meter"><span style="width:${done?100:46}%"></span></div></button>`}).join('')}
function collection(){const done=state.done.map(find);if(!done.length){$('#collection-content').innerHTML='<div class="empty-state">书架还是空的。<br>完成一首诗的深度学习后，它会按季节收在这里。</div>';return}$('#collection-content').innerHTML=`<div class="season-grid">${['春','夏','秋','冬'].map(s=>{const list=done.filter(p=>p.season===s);return `<section class="season"><h3>${s} · 诗笺</h3>${list.length?list.map(p=>`<p><button class="text-button" type="button" data-poem="${p.id}">${p.title}</button> · ${p.author}</p>`).join(''):'<p>等待一首诗落座</p>'}</section>`}).join('')}</div>`}
function question(){const q=state.quiz[state.index];$('#quiz-kicker').textContent=`《${find(state.current).title}》· 深度学习`;$('#quiz-progress').innerHTML=state.quiz.map((_,i)=>`<span class="${i<state.index?'done':''}"></span>`).join('');$('#question-number').textContent=`第 ${state.index+1} / 3 题`;$('#question-title').textContent=q[0];$('#answer-list').innerHTML=q[1].map((a,i)=>`<button class="answer" data-answer="${i}" type="button">${String.fromCharCode(65+i)}. ${a}</button>`).join('');$('#quiz-feedback').textContent='';$('#next-question').classList.add('hidden')}
function start(){state.quiz=[...find(state.current).quiz].sort(()=>Math.random()-.5);state.index=0;question();view('quiz')} function answer(i){const correct=state.quiz[state.index][2],buttons=[...document.querySelectorAll('.answer')],metric=state.stats[state.current]||{views:0,attempts:0,correct:0};metric.attempts+=1;if(i===correct)metric.correct+=1;state.stats[state.current]=metric;save();if(i!==correct){buttons[i].classList.add('wrong');$('#quiz-feedback').textContent='再想一想，读诗小笺里藏着答案。';return}buttons.forEach((b,n)=>{b.disabled=true;if(n===correct)b.classList.add('correct')});const last=state.index===2;$('#quiz-feedback').textContent=last?'全部答对，真好。':'答对了，继续下一题。';$('#next-question').textContent=last?'完成挑战':'下一题 →';$('#next-question').classList.remove('hidden')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)view(nav.dataset.nav);const poem=e.target.closest('[data-poem]');if(poem)open(poem.dataset.poem);const group=e.target.closest('[data-collection]');if(group){state.group=group.dataset.collection;state.chip='全部';document.querySelectorAll('.collection-tab').forEach(x=>x.classList.toggle('active',x===group));shelf()}const chapter=e.target.closest('[data-history-page]');if(chapter){state.historyPage=chapter.dataset.historyPage;shelf()}const chip=e.target.closest('[data-chip]');if(chip){state.chip=chip.dataset.chip;shelf()}const ans=e.target.closest('[data-answer]');if(ans&&!ans.disabled)answer(+ans.dataset.answer)});$('#daily-detail-button').onclick=()=>open(state.daily);$('#refresh-daily').onclick=()=>{const list=state.source==='all'?POEMS:POEMS.filter(p=>p.source===state.source);state.daily=list.find(p=>p.id!==state.daily)?.id||list[0].id;daily()};$('#source-select').onchange=e=>{state.source=e.target.value;$('#refresh-daily').click()};$('#poem-search').oninput=shelf;$('#detail-related').onclick=()=>$('#detail-related-list').scrollIntoView({behavior:'smooth'});$('#familiarity-toggle').onclick=()=>{const expanded=$('#familiarity-toggle').classList.toggle('expanded');$('#familiarity-toggle').setAttribute('aria-expanded',String(expanded))};$('#start-quiz').onclick=start;$('#quiz-back').onclick=()=>open(state.current);$('#next-question').onclick=()=>{if(state.index<2){state.index++;question()}else{$('#completion-modal').classList.remove('hidden')}};$('#modal-later').onclick=()=>{$('#completion-modal').classList.add('hidden');open(state.current)};$('#modal-complete').onclick=()=>{if(!state.done.includes(state.current))state.done.unshift(state.current);save();$('#completion-modal').classList.add('hidden');view('collection')};daily();
